### ISSUE TITLE
there is no the plugin file on zip

### ISSUE THREAD

**Issue by ovodesign82** [KevinGutowski/PixelFit#1]
Hi there 

thank you for such good stuff 

but don't see the .sketchplugin file on zip

thank you on advance

**Comment by KevinGutowski** [comment]
Hi @ovodesign82 you can download the plugin [here](https://github.com/KevinGutowski/PixelFit/releases/latest/download/togglepixelfitting.sketchplugin.zip). No need to download the whole repo to get the plugin.

**Comment by ovodesign82** [comment]
thanks already have done it 
all is ok
